// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ============================================================
  // WEB
  // ============================================================

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByyQhH_YeSvLL0FWwerEvExPIt2760jsM',
    appId: '1:229273857781:web:5eee3b04cde37b41cfdfbc',
    messagingSenderId: '229273857781',
    projectId: 'disasterdemo-698bf',
    authDomain: 'disasterdemo-698bf.firebaseapp.com',
    storageBucket: 'disasterdemo-698bf.firebasestorage.app',
    measurementId: 'G-72FCDXK3T8',
  );

  // ============================================================
  // ANDROID
  // ============================================================

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5KlRzpO0qcxD7RpVPCZ8HBeoFhNoQ95s',
    appId: '1:229273857781:android:7f6e08189b7b9fc6cfdfbc',
    messagingSenderId: '229273857781',
    projectId: 'disasterdemo-698bf',
    storageBucket: 'disasterdemo-698bf.firebasestorage.app',
  );

  // ============================================================
  // iOS
  // Firebase App: disaster-musa
  // ============================================================

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOSGn52nbDKs_jns4BWXk5zZ9zlgzGh0M',
    appId: '1:125207350139:ios:492a01f33c8613b9b34bde',
    messagingSenderId: '125207350139',
    projectId: 'disaster-musa',
    storageBucket: 'disaster-musa.firebasestorage.app',
    iosBundleId: 'com.musa.disaster',
  );
}
