// lib/widgets/chat_bubble.dart
import 'package:flutter/material.dart';
import '../config/colors.dart';
import '../models/chat_message.dart';
import 'chat_rich_text.dart';

/// ChatBubble widget is used to display individual chat messages
/// in the chatbot conversation interface. It visually differentiates
/// between messages sent by the user and responses generated by the system.
class ChatBubble extends StatelessWidget {
  const ChatBubble({super.key, required this.msg});

  /// Chat message model containing message text and sender role
  final ChatMessage msg;

  @override
  Widget build(BuildContext context) {

    /// Determine whether the message is sent by the user or by the system
    final isUser = msg.role == ChatRole.user;

    /// Set bubble background color based on message sender
    final bubbleColor = isUser ? AppColor.primary : Colors.white;

    /// Set text color for better readability
    final textColor = isUser ? Colors.white : AppColor.secondary;

    return Align(

      /// User messages appear on the right side
      /// Bot/system messages appear on the left side
      alignment: isUser ? Alignment.centerRight : Alignment.centerLeft,

      child: Container(
        margin: const EdgeInsets.only(bottom: 12),
        padding: const EdgeInsets.all(14),

        /// Limit bubble width for better readability
        constraints: const BoxConstraints(maxWidth: 340),

        /// Message bubble styling
        decoration: BoxDecoration(
          color: bubbleColor.withOpacity(isUser ? 0.92 : 0.95),
          borderRadius: BorderRadius.circular(18),

          /// Bot messages have a border while user messages do not
          border: Border.all(
            color: isUser ? Colors.transparent : AppColor.border,
          ),

          /// Shadow effect to give the bubble a card-like appearance
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.06),
              blurRadius: 14,
              offset: const Offset(0, 8),
            ),
          ],
        ),

        /// If the message contains a custom widget (child), display it.
        /// Otherwise display formatted text using ChatRichText.
        child: msg.child ??
            ChatRichText(
              text: msg.text ?? "",
              style: TextStyle(
                color: textColor,
                fontWeight: FontWeight.w700,
                height: 1.25,
                fontSize: 14,
              ),
            ),
      ),
    );
  }
}